Delete <Вхід> in sidebar,add url /admin for admin
klerik/AED-Map pull request #3
Opened 2022-02-07 18:07 UTC by volodymyryaniv

2022-02-07 18:38 UTC, klerik requested changes

2022-02-07 18:38 UTC, klerik commented on client/src/App.js
> +        <Route path="/admin" exact component={SignInModal} />
Please check linter for indents

2022-02-07 18:38 UTC, klerik commented on client/src/modules/Auth/submodules/SignIn/components/ButtonSignIn.js
> +    </Link>}
Please check linter for indents - and delete an unnecessary component that you are not using - Button

2022-02-07 18:38 UTC, klerik commented on client/src/shared/ModalWrapper/index.js
> +import { useHistory,useLocation } from 'react-router-dom';  //
delete an unnecessary component that you are not using

2022-02-07 19:26 UTC, volodymyryaniv commented on client/src/modules/Auth/submodules/SignIn/components/ButtonSignIn.js
> +    </Link>}
Fixed

2022-02-07 19:26 UTC, volodymyryaniv commented on client/src/shared/ModalWrapper/index.js
> +import { useHistory,useLocation } from 'react-router-dom';  //
Done

2022-02-08 07:06 UTC, klerik requested changes

2022-02-08 07:06 UTC, klerik commented on client/src/modules/Auth/submodules/SignIn/components/ButtonSignIn.js
> -const ButtonSignIn = ({ handleOpen, user }) => {
handleOpen was removed but I still see this prop in propTypes

2022-02-08 07:06 UTC, klerik commented on client/src/modules/Auth/submodules/SignIn/components/ButtonSignIn.js
> +    </>
ESLint: Missing parentheses around multilines JSX(react/jsx-wrap-multilines) - please, add parentheses

2022-02-08 07:24 UTC, volodymyryaniv commented on client/src/modules/Auth/submodules/SignIn/components/ButtonSignIn.js
> -const ButtonSignIn = ({ handleOpen, user }) => {
Done

2022-02-08 07:24 UTC, volodymyryaniv commented on client/src/modules/Auth/submodules/SignIn/components/ButtonSignIn.js
> +    </>
Fixed

2022-02-08 17:32 UTC, merged